CREATE TABLE IF NOT EXISTS service_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    grave_id BIGINT UNSIGNED NOT NULL,
    family_user_id BIGINT UNSIGNED NOT NULL,
    cemetery_id BIGINT UNSIGNED NOT NULL,
    service_id BIGINT UNSIGNED NOT NULL,
    service_name VARCHAR(120) NOT NULL,
    service_description VARCHAR(1000) NOT NULL DEFAULT '',
    price_centavos INT UNSIGNED NOT NULL,
    deceased_name VARCHAR(120) NOT NULL,
    headstone_name VARCHAR(120) NOT NULL,
    cemetery_name VARCHAR(120) NOT NULL,
    section_code VARCHAR(80) NOT NULL,
    block_code VARCHAR(80) NOT NULL DEFAULT '',
    row_code VARCHAR(80) NOT NULL DEFAULT '',
    lot_code VARCHAR(80) NOT NULL,
    preferred_date DATE NOT NULL,
    instructions VARCHAR(1000) NOT NULL DEFAULT '',
    status ENUM('requested', 'assigned', 'accepted', 'in_progress', 'awaiting_review', 'completed', 'issue_reported', 'cancelled') NOT NULL DEFAULT 'requested',
    caretaker_id BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY request_family_index (family_user_id, created_at),
    KEY request_caretaker_index (caretaker_id, status, created_at),
    KEY request_status_index (status, created_at),
    KEY request_grave_index (grave_id, created_at),
    CONSTRAINT request_grave_fk FOREIGN KEY (grave_id) REFERENCES grave_profiles(id),
    CONSTRAINT request_family_fk FOREIGN KEY (family_user_id) REFERENCES users(id),
    CONSTRAINT request_cemetery_fk FOREIGN KEY (cemetery_id) REFERENCES cemeteries(id),
    CONSTRAINT request_service_fk FOREIGN KEY (service_id) REFERENCES service_offerings(id),
    CONSTRAINT request_caretaker_fk FOREIGN KEY (caretaker_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS request_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    request_id BIGINT UNSIGNED NOT NULL,
    actor_user_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(30) DEFAULT NULL,
    to_status VARCHAR(30) NOT NULL,
    note VARCHAR(1000) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY request_event_order_index (request_id, created_at, id),
    CONSTRAINT request_event_request_fk FOREIGN KEY (request_id) REFERENCES service_requests(id) ON DELETE CASCADE,
    CONSTRAINT request_event_actor_fk FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
