<div class="page-heading">
    <div><p class="eyebrow">ADMINISTRATOR WORKSPACE</p><h1>Good day, administrator.</h1><p class="page-lead">A thoughtful overview of care across your pilot cemetery.</p></div>
    <span class="date-chip"><?= icon('calendar', 'size-4') ?> <?= e(date('F j, Y')) ?></span>
</div>
<section class="hero-card" aria-labelledby="hero-title">
    <div class="hero-copy"><span class="hero-kicker"><span class="hero-kicker-dot"></span> A NEW KIND OF CEMETERY CARE</span><h2 id="hero-title">A little care.<br><em>A lasting connection.</em></h2><p>Bring families, caretakers, and resting places together in one caring space.</p><a href="?page=caretakers" class="btn hero-button">Review caretakers <?= icon('arrow', 'size-4') ?></a></div>
    <div class="hero-art" aria-hidden="true"><svg viewBox="0 0 360 290" fill="none"><circle cx="190" cy="145" r="128" stroke="currentColor" opacity=".14"/><circle cx="190" cy="145" r="95" stroke="currentColor" opacity=".13"/><path d="M70 234c55-8 96-32 126-78 24-37 26-75 57-99" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M164 192c-34-3-45-29-40-45 29 3 41 19 40 45ZM196 156c-1-39 22-54 43-54-2 32-14 49-43 54ZM228 113c-22-13-17-42-5-51 22 15 23 31 5 51ZM121 216c-29 8-44-13-46-28 25-4 41 5 46 28Z" fill="currentColor" opacity=".25"/><path d="M195 155c13 31 38 42 72 40" stroke="currentColor" stroke-width="2"/><path d="M235 188c6-23 30-29 43-23-5 22-20 29-43 23Z" fill="currentColor" opacity=".22"/><circle cx="267" cy="65" r="4" fill="currentColor" opacity=".45"/><circle cx="79" cy="106" r="3" fill="currentColor" opacity=".45"/></svg></div>
    <div class="hero-side-note">CARE, CONNECTED<br>FROM ANYWHERE.</div>
</section>

<section class="section-block" aria-labelledby="snapshot-title"><div class="section-header"><div><p class="eyebrow">AT A GLANCE</p><h2 id="snapshot-title">Account snapshot</h2></div><span class="section-note">Live account data</span></div>
    <div class="stat-grid">
        <article class="stat-card"><span class="stat-icon stat-green"><?= icon('heart') ?></span><p>Family accounts</p><strong><?= $accountStats['families'] ?></strong><span class="stat-foot">Registered families</span></article>
        <article class="stat-card"><span class="stat-icon stat-gold"><?= icon('clock') ?></span><p>Pending caretakers</p><strong><?= $accountStats['pending'] ?></strong><span class="stat-foot">Need administrator review</span></article>
        <article class="stat-card"><span class="stat-icon stat-blue"><?= icon('shield') ?></span><p>Verified caretakers</p><strong><?= $accountStats['verified'] ?></strong><span class="stat-foot">Eligible for care assignments</span></article>
        <article class="stat-card"><span class="stat-icon stat-rose"><?= icon('users') ?></span><p>Total accounts</p><strong><?= $accountStats['total'] ?></strong><span class="stat-foot">All registered roles</span></article>
    </div>
</section>

<div class="content-grid">
    <section class="surface-card activity-card" aria-labelledby="activity-title"><div class="card-heading"><div><p class="eyebrow">CARE WORKFLOW</p><h2 id="activity-title">How care comes together</h2></div><span class="mini-pill">Core journey</span></div>
        <ol class="journey-list"><li><span class="journey-number">01</span><span><strong>A family registers a grave</strong><small>Names, section, lot, and reference photo make the location clear.</small></span><?= icon('check', 'size-4 journey-end') ?></li><li><span class="journey-number">02</span><span><strong>They request care</strong><small>The service and agreed details are shared with a verified caretaker.</small></span><?= icon('chevron', 'size-4 journey-end') ?></li><li><span class="journey-number">03</span><span><strong>Care is documented</strong><small>Before-and-after photos and a work note support family review.</small></span><?= icon('chevron', 'size-4 journey-end') ?></li></ol>
    </section>
    <aside class="surface-card next-card" aria-labelledby="next-title"><div class="card-heading"><div><p class="eyebrow">CARE COORDINATION</p><h2 id="next-title">Service requests</h2></div><?= icon('sparkle', 'size-5 muted-icon') ?></div><div class="next-illustration" aria-hidden="true"><?= icon('document', 'size-12') ?></div><h3>Connect care to a grave</h3><p>Review family requests and assign a verified caretaker with access to the cemetery.</p><a class="small-link" href="?page=requests">Manage requests</a></aside>
</div>
<section class="surface-card pilot-readiness" aria-labelledby="pilot-readiness-title"><div class="card-heading"><div><p class="eyebrow">PILOT CATALOG</p><h2 id="pilot-readiness-title">Available for care requests</h2></div></div><div class="readiness-grid"><a href="?page=cemeteries"><span class="stat-icon stat-green"><?= icon('pin') ?></span><strong><?= $catalogStats['cemeteries'] ?></strong><span>Active cemeteries</span><?= icon('arrow', 'size-4') ?></a><a href="?page=plots"><span class="stat-icon stat-gold"><?= icon('grid') ?></span><strong><?= $catalogStats['plots'] ?></strong><span>Active plot references</span><?= icon('arrow', 'size-4') ?></a><a href="?page=services"><span class="stat-icon stat-blue"><?= icon('flower') ?></span><strong><?= $catalogStats['services'] ?></strong><span>Active services</span><?= icon('arrow', 'size-4') ?></a></div></section>
<?php if ($recentCatalogEvents): ?><section class="surface-card catalog-activity" aria-labelledby="catalog-activity-title"><div class="card-heading"><div><p class="eyebrow">ADMINISTRATIVE HISTORY</p><h2 id="catalog-activity-title">Recent catalog changes</h2></div></div><ol><?php foreach ($recentCatalogEvents as $event): ?><li><span class="stat-icon stat-green"><?= icon('check', 'size-4') ?></span><div><strong><?= e(ucfirst($event['action'])) ?> <?= e(str_replace('_', ' ', $event['entity_type'])) ?></strong><p><?= e($event['summary']) ?></p></div><time><?= e(date('M j', strtotime($event['created_at']))) ?></time></li><?php endforeach; ?></ol></section><?php endif; ?>
