<?php $form = $catalogValues ?: ($editRecord ?? []); $isEditing = !empty($form['id']); ?>
<div class="page-heading"><div><p class="eyebrow">CEMETERY RECORDS</p><h1>Cemeteries.</h1><p class="page-lead">Create the partner cemetery record before adding plot references and services.</p></div><span class="date-chip"><?= icon('pin', 'size-4') ?> <?= count($cemeteries) ?> recorded</span></div>
<div class="admin-page-grid">
    <section class="surface-card admin-list-card" aria-labelledby="cemetery-list-title"><div class="card-heading"><div><p class="eyebrow">PARTNER LOCATIONS</p><h2 id="cemetery-list-title">Cemetery records</h2></div></div>
        <?php if (!$cemeteries): ?><div class="admin-empty"><?= icon('pin', 'size-8') ?><h3>No cemetery yet</h3><p>Add your pilot partner's real name and location to get started.</p></div><?php else: ?><div class="admin-record-list"><?php foreach ($cemeteries as $cemetery): ?><article class="admin-record"><div class="admin-record-head"><div><h3><?= e($cemetery['name']) ?></h3><p><?= e($cemetery['city']) ?>, <?= e($cemetery['province']) ?></p></div><?= status_badge(ucfirst($cemetery['status']), $cemetery['status'] === 'active' ? 'success' : 'neutral') ?></div><?php if ($cemetery['address'] !== ''): ?><p class="admin-record-detail"><?= e($cemetery['address']) ?></p><?php endif; ?><div class="admin-record-foot"><span><?= (int) $cemetery['plot_count'] ?> plot references · <?= (int) $cemetery['service_count'] ?> services</span><a href="?page=cemeteries&amp;edit=<?= (int) $cemetery['id'] ?>">Edit details <?= icon('arrow', 'size-4') ?></a></div></article><?php endforeach; ?></div><?php endif; ?>
    </section>
    <section class="surface-card admin-form-card" aria-labelledby="cemetery-form-title"><div class="card-heading"><div><p class="eyebrow"><?= $isEditing ? 'EDIT RECORD' : 'NEW RECORD' ?></p><h2 id="cemetery-form-title"><?= $isEditing ? 'Edit cemetery' : 'Add a cemetery' ?></h2></div><?php if ($isEditing): ?><a class="small-link" href="?page=cemeteries">New record</a><?php endif; ?></div><p class="admin-form-intro">Use the cemetery's official name and location as agreed with your partner. New records start active.</p>
        <?php if ($catalogErrors): ?><div class="alert auth-error" role="alert">Please correct the highlighted details.<?= isset($catalogErrors['form']) ? ' ' . e($catalogErrors['form']) : '' ?></div><?php endif; ?>
        <form method="post" action="?page=cemeteries" class="admin-form" novalidate><?= csrf_field() ?><input type="hidden" name="action" value="save_cemetery"><input type="hidden" name="id" value="<?= e((string) ($form['id'] ?? '')) ?>">
            <div class="form-field"><label for="cemetery-name">Cemetery name</label><input class="input input-bordered w-full" id="cemetery-name" name="name" maxlength="120" required value="<?= e((string) ($form['name'] ?? '')) ?>" placeholder="Official cemetery name"><small class="field-error"><?= e($catalogErrors['name'] ?? '') ?></small></div>
            <div class="admin-form-row"><div class="form-field"><label for="cemetery-city">City or municipality</label><input class="input input-bordered w-full" id="cemetery-city" name="city" maxlength="120" required value="<?= e((string) ($form['city'] ?? '')) ?>"><small class="field-error"><?= e($catalogErrors['city'] ?? '') ?></small></div><div class="form-field"><label for="cemetery-province">Province</label><input class="input input-bordered w-full" id="cemetery-province" name="province" maxlength="120" required value="<?= e((string) ($form['province'] ?? '')) ?>"><small class="field-error"><?= e($catalogErrors['province'] ?? '') ?></small></div></div>
            <div class="form-field"><label for="cemetery-address">Address or entrance details <span class="optional-label">Optional</span></label><textarea class="textarea textarea-bordered w-full" id="cemetery-address" name="address" maxlength="255" rows="2"><?= e((string) ($form['address'] ?? '')) ?></textarea><small class="field-error"><?= e($catalogErrors['address'] ?? '') ?></small></div>
            <?php if ($isEditing): ?><div class="form-field"><label for="cemetery-status">Status</label><select class="select select-bordered w-full" id="cemetery-status" name="status"><option value="active" <?= ($form['status'] ?? 'active') === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= ($form['status'] ?? '') === 'inactive' ? 'selected' : '' ?>>Inactive</option></select><small>Inactive cemeteries stay in the record but cannot receive new caretaker authorization.</small></div><?php endif; ?>
            <button class="btn btn-primary" type="submit"><?= $isEditing ? 'Save changes' : 'Add cemetery' ?> <?= icon('arrow', 'size-4') ?></button>
        </form>
    </section>
</div>
