<div class="page-heading"><div><p class="eyebrow">SHARED DESIGN SYSTEM</p><h1>Interface kit.</h1><p class="page-lead">The building blocks for every Puntod Care screen.</p></div><span class="date-chip"><?= icon('sparkle', 'size-4') ?> Phase 1</span></div>

<section class="kit-intro" aria-labelledby="kit-intro-title"><div><span class="kit-kicker">OUR DESIGN DIRECTION</span><h2 id="kit-intro-title">Quiet, clear, and caring.</h2><p>Deep navy from the Puntod Care logo anchors the interface. Soft blue, slate, and white keep everyday tasks calm and readable.</p></div><div class="kit-palette" aria-label="Brand color palette"><span class="swatch-navy" title="Deep navy"></span><span class="swatch-blue" title="Care blue"></span><span class="swatch-slate" title="Soft slate"></span><span class="swatch-white" title="White"></span></div></section>

<div class="kit-grid">
    <section class="surface-card kit-card" aria-labelledby="buttons-title"><div class="card-heading"><div><p class="eyebrow">01 · ACTIONS</p><h2 id="buttons-title">Buttons</h2></div></div><p class="kit-description">Primary actions stand out; quieter actions remain easy to find.</p><div class="kit-button-row"><button class="btn btn-primary" type="button" data-preview-action>Primary action <?= icon('arrow', 'size-4') ?></button><button class="btn btn-outline btn-primary" type="button" data-preview-action>Secondary action</button><button class="btn btn-ghost" type="button" data-preview-action>Text action</button></div><div class="kit-divider"></div><div class="kit-button-row"><button class="btn btn-primary btn-sm" type="button" data-preview-action>Small</button><button class="btn btn-primary" type="button" data-preview-action>Regular</button><button class="btn btn-primary" type="button" disabled>Unavailable</button></div></section>

    <section class="surface-card kit-card" aria-labelledby="status-title"><div class="card-heading"><div><p class="eyebrow">02 · FEEDBACK</p><h2 id="status-title">Status & messages</h2></div></div><p class="kit-description">Words accompany color so status is understandable at a glance.</p><div class="kit-badges"><?= status_badge('Completed', 'success') ?><?= status_badge('Awaiting review', 'warning') ?><?= status_badge('Scheduled', 'info') ?><?= status_badge('Pending', 'neutral') ?></div><div class="alert kit-alert" role="status"><?= icon('check', 'size-5') ?><span><strong>All set.</strong> An example of a clear success message.</span></div><div class="alert kit-alert kit-alert-warning" role="status"><?= icon('clock', 'size-5') ?><span><strong>Needs attention.</strong> An example of a helpful follow-up message.</span></div></section>

    <section class="surface-card kit-card kit-form-card" aria-labelledby="forms-title"><div class="card-heading"><div><p class="eyebrow">03 · DETAILS</p><h2 id="forms-title">Forms</h2></div></div><p class="kit-description">Try the example fields. The form checks input locally and does not save it.</p><form id="sample-form" class="sample-form" novalidate><div class="form-field"><label for="sample-name">Full name <span aria-hidden="true">*</span></label><input class="input input-bordered w-full" id="sample-name" name="name" type="text" autocomplete="name" required minlength="2" placeholder="e.g. Maria Dela Cruz" aria-describedby="sample-name-help sample-name-error"><small id="sample-name-help">Use the name shown on your record.</small><small class="field-error" id="sample-name-error" aria-live="polite"></small></div><div class="form-field"><label for="sample-email">Email address <span aria-hidden="true">*</span></label><input class="input input-bordered w-full" id="sample-email" name="email" type="email" autocomplete="email" required placeholder="name@example.com" aria-describedby="sample-email-error"><small class="field-error" id="sample-email-error" aria-live="polite"></small></div><div class="form-field"><label for="sample-service">Service to preview <span aria-hidden="true">*</span></label><select class="select select-bordered w-full" id="sample-service" name="service" required aria-describedby="sample-service-error"><option value="">Select a service</option><option value="inspection">Grave inspection</option><option value="cleaning">Grave cleaning</option><option value="flowers">Flower placement</option></select><small class="field-error" id="sample-service-error" aria-live="polite"></small></div><button class="btn btn-primary" type="submit">Check example form <?= icon('arrow', 'size-4') ?></button><p id="form-result" class="form-result" role="status" aria-live="polite"></p></form></section>

    <section class="surface-card kit-card" aria-labelledby="cards-title"><div class="card-heading"><div><p class="eyebrow">04 · INFORMATION</p><h2 id="cards-title">Content cards</h2></div></div><p class="kit-description">A familiar shape for a resting place, service, or recent update.</p><div class="mini-care-card"><div class="mini-care-icon"><?= icon('flower', 'size-8') ?></div><div><span>IN LOVING MEMORY</span><h3>Juan Dela Cruz</h3><p><?= icon('pin', 'size-4') ?> Garden of Peace · Lot 12</p><?= status_badge('Care documented', 'success') ?></div></div><div class="kit-divider"></div><p class="kit-note">Cards keep the person's name and location prominent, with status shown in clear words.</p></section>
</div>
<div id="preview-toast" class="preview-toast" role="status" aria-live="polite" hidden></div>
