<div class="page-heading"><div><p class="eyebrow">FAMILY WORKSPACE</p><h1>Always close in care.</h1><p class="page-lead">A place to remember, check in, and care from wherever you are.</p></div><span class="date-chip"><?= icon('calendar', 'size-4') ?> <?= e(date('F j, Y')) ?></span></div>

<section class="hero-card family-hero" aria-labelledby="family-hero-title"><div class="hero-copy"><span class="hero-kicker"><span class="hero-kicker-dot"></span> A SPACE FOR REMEMBRANCE</span><h2 id="family-hero-title">Distance changes where we are.<br><em>Never how much we care.</em></h2><p>Keep the important details, care history, and family updates together.</p><a href="<?= e(app_url('family', 'components')) ?>" class="btn hero-button">Explore the interface <?= icon('arrow', 'size-4') ?></a></div><div class="hero-art" aria-hidden="true"><svg viewBox="0 0 360 290" fill="none"><circle cx="187" cy="147" r="112" stroke="currentColor" opacity=".17"/><path d="M183 253V88m0 100c-38-15-51-47-50-65 31 8 47 28 50 65Zm0-55c30-6 46-30 50-54-31 3-47 19-50 54Zm0 27c38-9 58-32 62-54-35 3-57 19-62 54Z" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M183 188c-38-15-51-47-50-65 31 8 47 28 50 65Zm0-55c30-6 46-30 50-54-31 3-47 19-50 54Zm0 27c38-9 58-32 62-54-35 3-57 19-62 54Z" fill="currentColor" opacity=".22"/><path d="M98 253h179" stroke="currentColor" stroke-width="2"/><circle cx="77" cy="77" r="3" fill="currentColor"/></svg></div><div class="hero-side-note">NEAR IN EVERY<br>WAY THAT MATTERS.</div></section>

<section class="section-block" aria-labelledby="graves-title"><div class="section-header"><div><p class="eyebrow">PEOPLE WE REMEMBER</p><h2 id="graves-title">Your family graves</h2></div><span class="section-note">Illustrative sample profiles</span></div>
    <div class="profile-grid">
        <article class="profile-card"><div class="profile-art profile-art-one" aria-hidden="true"><?= icon('flower', 'size-14') ?></div><div class="profile-body"><span class="profile-kicker">IN LOVING MEMORY</span><h3>Juan Dela Cruz</h3><p>1945 – 2020</p><span class="profile-location"><?= icon('pin', 'size-4') ?> Garden of Peace · Lot 12</span><div class="profile-bottom"><?= status_badge('Care documented', 'success') ?><span>Sample profile</span></div></div></article>
        <article class="profile-card"><div class="profile-art profile-art-two" aria-hidden="true"><?= icon('flower', 'size-14') ?></div><div class="profile-body"><span class="profile-kicker">FOREVER IN OUR HEARTS</span><h3>Maria Dela Cruz</h3><p>1948 – 2022</p><span class="profile-location"><?= icon('pin', 'size-4') ?> Garden of Peace · Lot 13</span><div class="profile-bottom"><?= status_badge('Inspection due', 'warning') ?><span>Sample profile</span></div></div></article>
    </div>
</section>
<div class="content-grid"><section class="surface-card activity-card"><div class="card-heading"><div><p class="eyebrow">CARE MADE SIMPLE</p><h2>What you will be able to do</h2></div></div><ol class="journey-list"><li><span class="journey-number">01</span><span><strong>Keep grave details together</strong><small>Record names, cemetery locations, and photos.</small></span></li><li><span class="journey-number">02</span><span><strong>Request local care</strong><small>Ask a verified caretaker to inspect or maintain a grave.</small></span></li><li><span class="journey-number">03</span><span><strong>Review the result</strong><small>See before-and-after photos and raise concerns if needed.</small></span></li></ol></section><aside class="surface-card next-card"><div class="card-heading"><div><p class="eyebrow">A PROMISE OF CARE</p><h2>Every step, visible</h2></div><?= icon('heart', 'size-5 muted-icon') ?></div><div class="next-illustration family-next" aria-hidden="true"><?= icon('camera', 'size-12') ?></div><h3>Photos bring peace of mind</h3><p>Later phases will let families see the care performed and respond to a caretaker's report.</p><span class="phase-tag">PLANNED · PHASE 6</span></aside></div>
