<?php
$form = $graveValues ?: ($grave ?? []);
$editing = !empty($form['id']);
$availableCemeteries = array_filter($graveCemeteries, static fn (array $cemetery): bool => $cemetery['status'] === 'active');
$canSaveGrave = $availableCemeteries || $grave;
?>
<div class="page-heading"><div><p class="eyebrow">PRIVATE FAMILY RECORD</p><h1><?= $editing ? 'Edit grave details.' : 'Register a grave.' ?></h1><p class="page-lead">Start with the name on the headstone and the exact section and lot. Add reference photos after saving.</p></div><a class="btn btn-outline btn-primary btn-sm" href="<?= $editing ? '?page=grave&amp;id=' . (int) $form['id'] : '?page=graves' ?>">Back to <?= $editing ? 'profile' : 'my graves' ?></a></div>
<div class="review-intro" role="note"><?= icon('pin', 'size-5') ?><span>A map pin is optional. It helps with finding the area, but the headstone name and cemetery lot details are still needed to identify the correct grave.</span></div>
<div class="grave-form-layout"><form method="post" action="?page=grave-form<?= $editing ? '&amp;id=' . (int) $form['id'] : '' ?>" class="surface-card grave-form-card" novalidate><?= csrf_field() ?><input type="hidden" name="action" value="save_grave"><input type="hidden" name="id" value="<?= e((string) ($form['id'] ?? '')) ?>">
    <div class="card-heading"><div><p class="eyebrow">01 · PERSON</p><h2>Who we remember</h2></div></div>
    <?php if ($graveErrors): ?><div class="alert auth-error" role="alert">Please correct the highlighted details.</div><?php endif; ?>
    <div class="form-field"><label for="grave-name">Deceased person's full name</label><input class="input input-bordered w-full" id="grave-name" name="deceased_name" maxlength="120" required value="<?= e((string) ($form['deceased_name'] ?? '')) ?>" placeholder="e.g. Maria Dela Cruz"><small class="field-error"><?= e($graveErrors['deceased_name'] ?? '') ?></small></div>
    <div class="form-field"><label for="grave-headstone">Name shown on the headstone</label><input class="input input-bordered w-full" id="grave-headstone" name="headstone_name" maxlength="120" required value="<?= e((string) ($form['headstone_name'] ?? '')) ?>" placeholder="Enter the lettering as you know it"><small class="field-error"><?= e($graveErrors['headstone_name'] ?? '') ?></small></div>
    <div class="admin-form-row"><div class="form-field"><label for="grave-birth">Birth date <span class="optional-label">Optional</span></label><input class="input input-bordered w-full" id="grave-birth" name="birth_date" type="date" max="<?= e(date('Y-m-d')) ?>" value="<?= e((string) ($form['birth_date'] ?? '')) ?>"><small class="field-error"><?= e($graveErrors['birth_date'] ?? '') ?></small></div><div class="form-field"><label for="grave-death">Death date <span class="optional-label">Optional</span></label><input class="input input-bordered w-full" id="grave-death" name="death_date" type="date" max="<?= e(date('Y-m-d')) ?>" value="<?= e((string) ($form['death_date'] ?? '')) ?>"><small class="field-error"><?= e($graveErrors['death_date'] ?? '') ?></small></div></div>
    <div class="card-heading grave-form-section"><div><p class="eyebrow">02 · LOCATION</p><h2>Where to find the grave</h2></div></div>
    <?php if (!$availableCemeteries && !$grave): ?><div class="alert auth-info" role="note">The administrator needs to add an active cemetery before your family can register a grave.</div><?php endif; ?>
    <div class="form-field"><label for="grave-cemetery">Cemetery</label><select class="select select-bordered w-full" id="grave-cemetery" name="cemetery_id" required><option value="">Choose a cemetery</option><?php foreach ($graveCemeteries as $cemetery): ?><?php if ($cemetery['status'] === 'active' || ($grave && (int) $grave['cemetery_id'] === (int) $cemetery['id'])): ?><option value="<?= (int) $cemetery['id'] ?>" <?= (string) ($form['cemetery_id'] ?? '') === (string) $cemetery['id'] ? 'selected' : '' ?>><?= e($cemetery['name']) ?> · <?= e($cemetery['city']) ?><?= $cemetery['status'] !== 'active' ? ' (inactive)' : '' ?></option><?php endif; ?><?php endforeach; ?></select><small class="field-error"><?= e($graveErrors['cemetery_id'] ?? '') ?></small></div>
    <div class="admin-form-row"><div class="form-field"><label for="grave-section">Section</label><input class="input input-bordered w-full" id="grave-section" name="section_code" maxlength="80" required value="<?= e((string) ($form['section_code'] ?? '')) ?>" placeholder="e.g. Garden A"><small class="field-error"><?= e($graveErrors['section_code'] ?? '') ?></small></div><div class="form-field"><label for="grave-lot">Lot or grave number</label><input class="input input-bordered w-full" id="grave-lot" name="lot_code" maxlength="80" required value="<?= e((string) ($form['lot_code'] ?? '')) ?>" placeholder="e.g. 12"><small class="field-error"><?= e($graveErrors['lot_code'] ?? '') ?></small></div></div>
    <div class="admin-form-row"><div class="form-field"><label for="grave-block">Block <span class="optional-label">Optional</span></label><input class="input input-bordered w-full" id="grave-block" name="block_code" maxlength="80" value="<?= e((string) ($form['block_code'] ?? '')) ?>"><small class="field-error"><?= e($graveErrors['block_code'] ?? '') ?></small></div><div class="form-field"><label for="grave-row">Row <span class="optional-label">Optional</span></label><input class="input input-bordered w-full" id="grave-row" name="row_code" maxlength="80" value="<?= e((string) ($form['row_code'] ?? '')) ?>"><small class="field-error"><?= e($graveErrors['row_code'] ?? '') ?></small></div></div>
    <div class="form-field"><label for="grave-note">Landmark or finding note <span class="optional-label">Optional</span></label><textarea class="textarea textarea-bordered w-full" id="grave-note" name="location_note" rows="3" maxlength="500" placeholder="e.g. Beside the east path, under the acacia tree"><?= e((string) ($form['location_note'] ?? '')) ?></textarea><small class="field-error"><?= e($graveErrors['location_note'] ?? '') ?></small></div>
    <div class="card-heading grave-form-section"><div><p class="eyebrow">03 · OPTIONAL PIN</p><h2>Coordinates</h2></div></div><p class="admin-form-intro">Enter both coordinates only if you know the grave's position. If you are standing at the grave, you can ask your device for its current location.</p>
    <div class="admin-form-row"><div class="form-field"><label for="grave-latitude">Latitude</label><input class="input input-bordered w-full" id="grave-latitude" name="latitude" inputmode="decimal" value="<?= e((string) ($form['latitude'] ?? '')) ?>" placeholder="8.4822000"></div><div class="form-field"><label for="grave-longitude">Longitude</label><input class="input input-bordered w-full" id="grave-longitude" name="longitude" inputmode="decimal" value="<?= e((string) ($form['longitude'] ?? '')) ?>" placeholder="124.6470000"></div></div><small class="field-error"><?= e($graveErrors['coordinates'] ?? '') ?></small><button class="btn btn-outline btn-primary btn-sm grave-location-button" type="button" data-grave-location>Use my current location</button><p class="grave-location-feedback" data-grave-location-feedback role="status"></p>
    <div class="grave-form-actions"><button class="btn btn-primary" type="submit" <?= !$canSaveGrave ? 'disabled' : '' ?>><?= $editing ? 'Save grave details' : 'Register grave' ?> <?= icon('arrow', 'size-4') ?></button></div>
</form><aside class="surface-card grave-form-aside"><div class="next-illustration family-next" aria-hidden="true"><?= icon('shield', 'size-10') ?></div><h2>Private to your family account</h2><p>Your grave profile and reference photos are shown only after you sign in. Keep the headstone name and lot details accurate so the right grave can be confirmed before future work.</p><p>Photo uploads become available immediately after you save the profile.</p></aside></div>
