<?php $form = $catalogValues ?: ($editRecord ?? []); ?>
<div class="page-heading"><div><p class="eyebrow">PILOT SETUP · 02</p><h1>Plot references.</h1><p class="page-lead">Record exact section and lot details so future grave profiles can point to the right place.</p></div><a class="btn btn-outline btn-primary btn-sm" href="?page=cemeteries">Manage cemeteries</a></div>
<div class="review-intro" role="note"><?= icon('pin', 'size-5') ?><span>These are cemetery location references. A family's grave profile and headstone photo are added in Phase 4; a map pin alone never confirms the exact grave.</span></div>
<div class="admin-page-grid">
    <section class="surface-card admin-list-card" aria-labelledby="plot-list-title"><div class="card-heading"><div><p class="eyebrow">LOCATION INDEX</p><h2 id="plot-list-title">Recorded plots</h2></div><span class="mini-pill">Up to 100 results</span></div>
        <form class="admin-filters" method="get"><input type="hidden" name="page" value="plots"><label class="sr-only" for="plot-filter-cemetery">Filter by cemetery</label><select class="select select-bordered" id="plot-filter-cemetery" name="cemetery_id"><option value="">All cemeteries</option><?php foreach ($cemeteries as $cemetery): ?><option value="<?= (int) $cemetery['id'] ?>" <?= $filterCemeteryId === (int) $cemetery['id'] ? 'selected' : '' ?>><?= e($cemetery['name']) ?></option><?php endforeach; ?></select><label class="sr-only" for="plot-search">Search plot code</label><input class="input input-bordered" id="plot-search" name="q" maxlength="80" value="<?= e($catalogSearch) ?>" placeholder="Search section or lot"><button class="btn btn-outline btn-primary btn-sm" type="submit">Search</button></form>
        <?php if (!$plots): ?><div class="admin-empty"><?= icon('grid', 'size-8') ?><h3>No matching plots</h3><p>Use the form to create your first section and lot reference.</p></div><?php else: ?><div class="admin-record-list"><?php foreach ($plots as $plot): ?><article class="admin-record"><div class="admin-record-head"><div><h3>Section <?= e($plot['section_code']) ?> · Lot <?= e($plot['lot_code']) ?></h3><p><?= e($plot['cemetery_name']) ?> · <?= e($plot['cemetery_city']) ?></p></div><?= status_badge(ucfirst($plot['status']), $plot['status'] === 'active' && $plot['cemetery_status'] === 'active' ? 'success' : 'neutral') ?></div><p class="admin-record-detail">Block <?= e($plot['block_code'] ?: '—') ?> · Row <?= e($plot['row_code'] ?: '—') ?><?= $plot['landmark'] ? ' · ' . e($plot['landmark']) : '' ?></p><div class="admin-record-foot"><span>Location reference #<?= (int) $plot['id'] ?></span><a href="?page=plots&amp;edit=<?= (int) $plot['id'] ?>">Edit reference <?= icon('arrow', 'size-4') ?></a></div></article><?php endforeach; ?></div><?php endif; ?>
    </section>
    <section class="surface-card admin-form-card" aria-labelledby="plot-form-title"><div class="card-heading"><div><p class="eyebrow"><?= $editRecord || $catalogValues ? 'EDIT REFERENCE' : 'NEW REFERENCE' ?></p><h2 id="plot-form-title"><?= $editRecord || !empty($form['id']) ? 'Edit plot' : 'Add a plot' ?></h2></div><?php if ($editRecord || $catalogValues): ?><a class="small-link" href="?page=plots">New reference</a><?php endif; ?></div><p class="admin-form-intro">Section and lot are required. Add block and row when the cemetery uses them.</p>
        <?php if (!$cemeteries): ?><div class="alert auth-info" role="note">Add a cemetery before recording plots.</div><?php endif; ?>
        <?php if ($catalogErrors): ?><div class="alert auth-error" role="alert">Please correct the highlighted details.<?= isset($catalogErrors['form']) ? ' ' . e($catalogErrors['form']) : '' ?></div><?php endif; ?>
        <form method="post" action="?page=plots" class="admin-form" novalidate><?= csrf_field() ?><input type="hidden" name="action" value="save_plot"><input type="hidden" name="id" value="<?= e((string) ($form['id'] ?? '')) ?>">
            <div class="form-field"><label for="plot-cemetery">Cemetery</label><select class="select select-bordered w-full" id="plot-cemetery" name="cemetery_id" required><option value="">Choose a cemetery</option><?php foreach ($cemeteries as $cemetery): ?><option value="<?= (int) $cemetery['id'] ?>" <?= (string) ($form['cemetery_id'] ?? '') === (string) $cemetery['id'] ? 'selected' : '' ?>><?= e($cemetery['name']) ?> · <?= e($cemetery['city']) ?></option><?php endforeach; ?></select><small class="field-error"><?= e($catalogErrors['cemetery_id'] ?? '') ?></small></div>
            <div class="admin-form-row"><div class="form-field"><label for="plot-section">Section</label><input class="input input-bordered w-full" id="plot-section" name="section_code" maxlength="80" required value="<?= e((string) ($form['section_code'] ?? '')) ?>"><small class="field-error"><?= e($catalogErrors['section_code'] ?? '') ?></small></div><div class="form-field"><label for="plot-lot">Lot or grave number</label><input class="input input-bordered w-full" id="plot-lot" name="lot_code" maxlength="80" required value="<?= e((string) ($form['lot_code'] ?? '')) ?>"><small class="field-error"><?= e($catalogErrors['lot_code'] ?? '') ?></small></div></div>
            <div class="admin-form-row"><div class="form-field"><label for="plot-block">Block <span class="optional-label">Optional</span></label><input class="input input-bordered w-full" id="plot-block" name="block_code" maxlength="80" value="<?= e((string) ($form['block_code'] ?? '')) ?>"><small class="field-error"><?= e($catalogErrors['block_code'] ?? '') ?></small></div><div class="form-field"><label for="plot-row">Row <span class="optional-label">Optional</span></label><input class="input input-bordered w-full" id="plot-row" name="row_code" maxlength="80" value="<?= e((string) ($form['row_code'] ?? '')) ?>"><small class="field-error"><?= e($catalogErrors['row_code'] ?? '') ?></small></div></div>
            <div class="form-field"><label for="plot-landmark">Landmark or finding note <span class="optional-label">Optional</span></label><textarea class="textarea textarea-bordered w-full" id="plot-landmark" name="landmark" maxlength="255" rows="2"><?= e((string) ($form['landmark'] ?? '')) ?></textarea><small class="field-error"><?= e($catalogErrors['landmark'] ?? '') ?></small></div>
            <div class="form-field"><label for="plot-status">Status</label><select class="select select-bordered w-full" id="plot-status" name="status"><option value="active" <?= ($form['status'] ?? 'active') === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= ($form['status'] ?? '') === 'inactive' ? 'selected' : '' ?>>Inactive</option></select></div>
            <button class="btn btn-primary" type="submit" <?= !$cemeteries ? 'disabled' : '' ?>><?= $editRecord || !empty($form['id']) ? 'Save changes' : 'Add plot reference' ?> <?= icon('arrow', 'size-4') ?></button>
        </form>
    </section>
</div>
