<div class="page-heading"><div><p class="eyebrow">CARE FOR A LOVED ONE</p><h1>Request care.</h1><p class="page-lead">Choose a service for <?= e($requestGrave['deceased_name']) ?> and tell us when you would prefer it.</p></div><a class="btn btn-outline btn-primary btn-sm" href="?page=grave&amp;id=<?= (int) $requestGrave['id'] ?>">Back to grave</a></div>
<div class="review-intro" role="note"><?= icon('shield', 'size-5') ?><span>The price shown is a pilot estimate saved with this request. No payment or booking confirmation happens here. An administrator will assign an eligible caretaker, who can then view the grave’s reference photos while the job is active.</span></div>
<div class="grave-form-layout"><form method="post" action="?page=request-new&amp;grave_id=<?= (int) $requestGrave['id'] ?>" class="surface-card grave-form-card" novalidate><?= csrf_field() ?><input type="hidden" name="action" value="create_request"><input type="hidden" name="grave_id" value="<?= (int) $requestGrave['id'] ?>">
    <div class="card-heading"><div><p class="eyebrow">01 · SERVICE</p><h2>Choose the care</h2></div></div>
    <?php if ($requestErrors): ?><div class="alert auth-error" role="alert">Please correct the highlighted details.</div><?php endif; ?>
    <?php if (!$availableServices): ?><div class="alert auth-info" role="note">No active service is available for this cemetery yet. Ask the administrator to add one.</div><?php endif; ?>
    <div class="form-field"><label for="request-service">Service</label><select class="select select-bordered w-full" id="request-service" name="service_id" data-request-service required><option value="">Choose a service</option><?php foreach ($availableServices as $service): ?><?php $choice = (int) $service['id'] . ':' . (int) $service['price_centavos']; ?><option value="<?= e($choice) ?>" data-price="<?= e(catalog_money((int) $service['price_centavos'])) ?>" data-description="<?= e($service['description']) ?>" <?= ($requestValues['service_id'] ?? '') === $choice ? 'selected' : '' ?>><?= e($service['name']) ?> · <?= e(catalog_money((int) $service['price_centavos'])) ?></option><?php endforeach; ?></select><small class="field-error"><?= e($requestErrors['service_id'] ?? '') ?></small></div>
    <div class="request-price-panel"><span>Pilot estimate for this service</span><strong data-request-price>Choose a service</strong><p data-request-description>See the work included before you submit.</p></div>
    <div class="card-heading grave-form-section"><div><p class="eyebrow">02 · PREFERENCE</p><h2>Plan the visit</h2></div></div>
    <div class="form-field"><label for="request-date">Preferred date</label><input class="input input-bordered w-full" id="request-date" name="preferred_date" type="date" min="<?= e(date('Y-m-d')) ?>" max="<?= e(date('Y-m-d', strtotime('+1 year'))) ?>" required value="<?= e((string) ($requestValues['preferred_date'] ?? '')) ?>"><small class="field-error"><?= e($requestErrors['preferred_date'] ?? '') ?></small><small>This is a preference; the caretaker has not accepted a schedule yet.</small></div>
    <div class="form-field"><label for="request-instructions">Instructions <span class="optional-label">Optional</span></label><textarea class="textarea textarea-bordered w-full" id="request-instructions" name="instructions" rows="4" maxlength="1000" placeholder="Share access details or anything the caretaker should know."><?= e((string) ($requestValues['instructions'] ?? '')) ?></textarea><small class="field-error"><?= e($requestErrors['instructions'] ?? '') ?></small></div>
    <label class="request-check"><input type="checkbox" name="price_ack" value="1" <?= ($requestValues['price_ack'] ?? '') === '1' ? 'checked' : '' ?>><span>I reviewed the displayed pilot price and understand no payment is collected here.</span></label><small class="field-error"><?= e($requestErrors['price_ack'] ?? '') ?></small>
    <div class="grave-form-actions"><button class="btn btn-primary" type="submit" <?= !$availableServices ? 'disabled' : '' ?>>Submit care request <?= icon('arrow', 'size-4') ?></button></div>
</form><aside class="surface-card grave-form-aside"><div class="next-illustration family-next" aria-hidden="true"><?= icon('pin', 'size-10') ?></div><p class="eyebrow">GRAVE TO BE CARED FOR</p><h2><?= e($requestGrave['deceased_name']) ?></h2><p><strong><?= e($requestGrave['cemetery_name']) ?></strong><br>Section <?= e($requestGrave['section_code']) ?> · Lot <?= e($requestGrave['lot_code']) ?></p><p>Headstone: <?= e($requestGrave['headstone_name']) ?></p><p>The caretaker must confirm these details before starting.</p></aside></div>
