<?php
$form = $catalogValues ?: ($editRecord ?? []);
$isEditing = !empty($form['id']);
if (!$catalogValues && $editRecord) $form['price'] = number_format((int) $editRecord['price_centavos'] / 100, 2, '.', '');
?>
<div class="page-heading"><div><p class="eyebrow">CARE OFFERINGS</p><h1>Service catalog.</h1><p class="page-lead">Define what families can request at each cemetery and record a starting price.</p></div><a class="btn btn-outline btn-primary btn-sm" href="?page=cemeteries">Manage cemeteries</a></div>
<div class="review-intro" role="note"><?= icon('document', 'size-5') ?><span>All listed prices are pilot estimates in Philippine pesos. Validate them with your cemetery partner and providers before using them for real payments. Puntod Care does not take payments.</span></div>
<div class="admin-page-grid">
    <section class="surface-card admin-list-card" aria-labelledby="services-list-title"><div class="card-heading"><div><p class="eyebrow">CARE OFFERINGS</p><h2 id="services-list-title">Services and prices</h2></div><span class="mini-pill">Up to 100 results</span></div>
        <form class="admin-filters" method="get"><input type="hidden" name="page" value="services"><label class="sr-only" for="service-filter-cemetery">Filter by cemetery</label><select class="select select-bordered" id="service-filter-cemetery" name="cemetery_id"><option value="">All cemeteries</option><?php foreach ($cemeteries as $cemetery): ?><option value="<?= (int) $cemetery['id'] ?>" <?= $filterCemeteryId === (int) $cemetery['id'] ? 'selected' : '' ?>><?= e($cemetery['name']) ?></option><?php endforeach; ?></select><button class="btn btn-outline btn-primary btn-sm" type="submit">Filter</button></form>
        <?php if (!$services): ?><div class="admin-empty"><?= icon('flower', 'size-8') ?><h3>No services yet</h3><p>Add a care service and its pilot estimate when you have agreed on a starting offering.</p></div><?php else: ?><div class="admin-record-list"><?php foreach ($services as $service): ?><article class="admin-record"><div class="admin-record-head"><div><h3><?= e($service['name']) ?></h3><p><?= e($service['cemetery_name']) ?> · <?= e($service['cemetery_city']) ?></p></div><?= status_badge(ucfirst($service['status']), $service['status'] === 'active' && $service['cemetery_status'] === 'active' ? 'success' : 'neutral') ?></div><?php if ($service['description'] !== ''): ?><p class="admin-record-detail"><?= e($service['description']) ?></p><?php endif; ?><div class="service-price-row"><strong><?= e(catalog_money((int) $service['price_centavos'])) ?></strong><span>Pilot estimate</span></div><div class="admin-record-foot"><span>Price changes are recorded</span><a href="?page=services&amp;edit=<?= (int) $service['id'] ?>">Edit offering <?= icon('arrow', 'size-4') ?></a></div></article><?php endforeach; ?></div><?php endif; ?>
    </section>
    <div class="admin-right-stack"><section class="surface-card admin-form-card" aria-labelledby="service-form-title"><div class="card-heading"><div><p class="eyebrow"><?= $isEditing ? 'EDIT OFFERING' : 'NEW OFFERING' ?></p><h2 id="service-form-title"><?= $isEditing ? 'Edit service' : 'Add a service' ?></h2></div><?php if ($isEditing): ?><a class="small-link" href="?page=services">New service</a><?php endif; ?></div><p class="admin-form-intro">Describe the work clearly so families understand what the quoted amount covers. New offerings start active.</p>
        <?php if (!$cemeteries): ?><div class="alert auth-info" role="note">Add a cemetery before recording services.</div><?php endif; ?>
        <?php if ($catalogErrors): ?><div class="alert auth-error" role="alert">Please correct the highlighted details.<?= isset($catalogErrors['form']) ? ' ' . e($catalogErrors['form']) : '' ?></div><?php endif; ?>
        <form method="post" action="?page=services" class="admin-form" novalidate><?= csrf_field() ?><input type="hidden" name="action" value="save_service"><input type="hidden" name="id" value="<?= e((string) ($form['id'] ?? '')) ?>">
            <div class="form-field"><label for="service-cemetery">Cemetery</label><select class="select select-bordered w-full" id="service-cemetery" name="cemetery_id" required><option value="">Choose a cemetery</option><?php foreach ($cemeteries as $cemetery): ?><option value="<?= (int) $cemetery['id'] ?>" <?= (string) ($form['cemetery_id'] ?? '') === (string) $cemetery['id'] ? 'selected' : '' ?>><?= e($cemetery['name']) ?> · <?= e($cemetery['city']) ?></option><?php endforeach; ?></select><small class="field-error"><?= e($catalogErrors['cemetery_id'] ?? '') ?></small></div>
            <div class="form-field"><label for="service-name">Service name</label><input class="input input-bordered w-full" id="service-name" name="name" maxlength="120" required value="<?= e((string) ($form['name'] ?? '')) ?>" placeholder="e.g. Grave cleaning"><small class="field-error"><?= e($catalogErrors['name'] ?? '') ?></small></div>
            <div class="form-field"><label for="service-description">What is included <span class="optional-label">Optional</span></label><textarea class="textarea textarea-bordered w-full" id="service-description" name="description" maxlength="1000" rows="3" placeholder="Describe the task, supplies, and expected result."><?= e((string) ($form['description'] ?? '')) ?></textarea><small class="field-error"><?= e($catalogErrors['description'] ?? '') ?></small></div>
            <div class="form-field"><label for="service-price">Pilot price (PHP)</label><input class="input input-bordered w-full" id="service-price" name="price" inputmode="decimal" required value="<?= e((string) ($form['price'] ?? '')) ?>" placeholder="500.00"><small class="field-error"><?= e($catalogErrors['price'] ?? '') ?></small><small>Enter pesos; for example, 500.00. This is an estimate until validated.</small></div>
            <?php if ($isEditing): ?><div class="form-field"><label for="service-status">Availability</label><select class="select select-bordered w-full" id="service-status" name="status"><option value="active" <?= ($form['status'] ?? 'active') === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= ($form['status'] ?? '') === 'inactive' ? 'selected' : '' ?>>Inactive</option></select><small>Inactive offerings remain in the catalog history but should not be offered for new requests.</small></div><?php endif; ?>
            <button class="btn btn-primary" type="submit" <?= !$cemeteries ? 'disabled' : '' ?>><?= $isEditing ? 'Save changes' : 'Add service' ?> <?= icon('arrow', 'size-4') ?></button>
        </form></section>
        <?php if (!empty($priceHistory)): ?><section class="surface-card history-card"><div class="card-heading"><div><p class="eyebrow">RECORDED CHANGES</p><h2>Price history</h2></div></div><ol class="price-history"><?php foreach ($priceHistory as $entry): ?><li><strong><?= e(catalog_money((int) $entry['price_centavos'])) ?></strong><span><?= e(date('M j, Y', strtotime($entry['changed_at']))) ?> · <?= e($entry['changed_by_name']) ?></span></li><?php endforeach; ?></ol></section><?php endif; ?>
    </div>
</div>
